CREATE TABLE KTS_COURSES (
    C_ID VARCHAR(50),
    C_TITLE VARCHAR(255),
    C_DESC VARCHAR(1000),
    C_PRICE VARCHAR(100),
    C_LINK VARCHAR(1000),
    C_TRENDING VARCHAR(500)
); 

ALTER TABLE KTS_COURSES 
ADD PRIMARY KEY (C_ID);

CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    full_name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE KTS_FAV_COURSE (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    COURSE_ID VARCHAR(36) NOT NULL
);

ALTER TABLE USERS
ADD COLUMN EMAIL_VERIFIED BOOLEAN DEFAULT FALSE,
ADD COLUMN EMAIL_OTP VARCHAR(6),
ADD COLUMN OTP_EXPIRY DATETIME;
